image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-DskipTests"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - config
  - deploy

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS package
    - mkdir -p deployment/ait/sw/fair-wizard
    - cp target/fair-wizard-*.jar deployment/ait/sw/fair-wizard/fair-wizard.jar
  artifacts:
    paths:
      - deployment/ait/sw/fair-wizard/fair-wizard.jar

copy-config:
  image: maven:3.6-jdk-11
  stage: config
  script:
    - git clone https://$FW_INTERNAL_USER:$FW_INTERNAL_PASS@gitlab.ebi.ac.uk/biosamples/fair-wizard-internal.git
    - cp -r fair-wizard-internal/www/* deployment/
  only:
    - master
    - dev

deploy:
  image: ubuntu
  stage: deploy
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$BSD_PROD_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan wp-p2m-27.ebi.ac.uk >> ~/.ssh/known_hosts
    - ssh-keyscan wp-p1m-27.ebi.ac.uk >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - scp -r -v -o StrictHostKeyChecking=no deployment/* bsd_prod@wp-p2m-27.ebi.ac.uk:~/
    - ssh -v -o StrictHostKeyChecking=no bsd_prod@wp-p2m-27.ebi.ac.uk "~/ait/tools/monit-5.32.0/bin restart fair-wizard"
    - scp -r -v -o StrictHostKeyChecking=no deployment/* bsd_prod@wp-p1m-27.ebi.ac.uk:~/
    - ssh -v -o StrictHostKeyChecking=no bsd_prod@wp-p1m-27.ebi.ac.uk "~/ait/tools/monit-5.32.0/bin restart fair-wizard"
  when: manual
  only:
    - master
    - dev
